POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"h.saiko0t@gmail.com",
    "password":"Password123"
}

###
GET http://localhost:3000/users/519111c6-4a56-45d7-a8ce-bd8930cf2260
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ4M2MzY2JlLWRiN2QtNGM4NC05ZTA3LWMwMmNhMjg1MmYwNyIsImVtYWlsIjoib21jcmlzdGh5YW5AZ21haWwuY29tIiwiaWF0IjoxNzU2MDcxNzczLCJleHAiOjE3NTYwNzUzNzN9.QfzmytKox0TLB1aJVSKfZCkjSPgbMzkop4YuoKpmbhk; Max-Age=3600; Path=/; Expires=Sun, 24 Aug 2025 22:42:53 GMT; HttpOnly; Secure; SameSite=Lax

###
DELETE http://localhost:3000/u/e.a5hGhv5E
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUxOTExMWM2LTRhNTYtNDVkNy1hOGNlLWJkODkzMGNmMjI2MCIsImVtYWlsIjoiaC5zYWlrbzB0QGdtYWlsLmNvbSIsImlhdCI6MTc1NjA3MjAwMSwiZXhwIjoxNzU2MDc1NjAxfQ.lNgslOzNIdn06Gos1CmN6A2pJcwXL1DSc5MeRQTbkYE; Path=/; HttpOnly; Secure; SameSite=Lax

###
POST http://localhost:3000/auth/logout
###
POST http://localhost:3000/u
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUxOTExMWM2LTRhNTYtNDVkNy1hOGNlLWJkODkzMGNmMjI2MCIsImVtYWlsIjoiaC5zYWlrbzB0QGdtYWlsLmNvbSIsImlhdCI6MTc1NjA3MjAwMSwiZXhwIjoxNzU2MDc1NjAxfQ.lNgslOzNIdn06Gos1CmN6A2pJcwXL1DSc5MeRQTbkYE; Path=/; HttpOnly; Secure; SameSite=Lax
Content-Type: application/json

{
    "url": "https://chatgpt.com/c/68ab1fdc-3394-8323-9e70-b251552ba851"
}
